name: Sync to HF Playground
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Setup Git LFS
        run: git lfs install
        
      - name: Push to Hugging Face Playground
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf-playground https://sbenfenatti:$HF_TOKEN@huggingface.co/spaces/sbenfenatti/radiologIA_playground
          git push hf-playground main --force